/*

 BALLSPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char ballSprite[] =
{
  0x3C,0x3C,0x72,0x42,0xA1,0xC1,0xA1,0xC1,
  0xB3,0xC1,0x9F,0xE1,0x42,0x7E,0x3C,0x3C,
  0x81,0x00,0x7E,0x01,0x7E,0x01,0x7E,0x01,
  0x7E,0x01,0x7E,0x01,0x7E,0x01,0x81,0x7E
};

/* End of BALLSPRITE.C */
